CREATE TABLE IF NOT EXISTS appointments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    expert_id UUID NOT NULL REFERENCES users(id),
    parent_id UUID REFERENCES users(id),
    child_id UUID REFERENCES children(id) ON DELETE SET NULL,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    duration INTEGER NOT NULL DEFAULT 50,
    type VARCHAR(30) NOT NULL DEFAULT 'FACE_TO_FACE',
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    notes TEXT,
    session_notes TEXT,
    cancellation_reason TEXT,
    meeting_link VARCHAR(500),
    calendar_event_id UUID REFERENCES calendar_events(id) ON DELETE SET NULL,
    rating INTEGER,
    rating_comment TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
