CREATE TABLE IF NOT EXISTS institutions (
    id           VARCHAR(100) PRIMARY KEY,
    name         TEXT         NOT NULL,
    city         TEXT,
    category     VARCHAR(50),
    specialties  TEXT,
    description  TEXT,
    phone        VARCHAR(50),
    email        VARCHAR(200),
    website      TEXT,
    source_url   TEXT,
    source_label TEXT,
    address      TEXT,
    sgk_contract BOOLEAN,
    free_service BOOLEAN,
    age_range    VARCHAR(50),
    services     TEXT,
    notes        TEXT
);

INSERT INTO institutions VALUES
-- STK, Vakıf & Dernekler
('tohum','Tohum Otizm Vakfı','İstanbul','ngo','Otizm Eğitimi|||Aile Desteği|||Farkındalık','Türkiye''nin en köklü otizm vakfı. Okul öncesi ve okul çağı çocuklar için erken müdahale programları, aile destek grupları, öğretmen eğitimleri ve ulusal farkındalık kampanyaları yürütür.','0212 257 75 00',NULL,'https://www.tohumotizm.org.tr',NULL,NULL,'Etiler, Beşiktaş, İstanbul',NULL,NULL,NULL,'Erken Müdahale|||Aile Destek Grubu|||Öğretmen Eğitimi|||Farkındalık Kampanyaları',NULL),
('otizmder','Otizm Derneği (OTİZM-DER)','Ankara','ngo','Hukuki Destek|||Savunuculuk|||Haklar','Otizm tanılı bireylerin ve ailelerinin haklarını savunur. Hukuki rehberlik, eğitim hakkı danışmanlığı ve BEP süreci desteği sunar.','0312 430 12 78','info@otizmder.org.tr','https://www.otizmder.org.tr',NULL,NULL,NULL,NULL,NULL,NULL,'Hukuki Danışmanlık|||Hak Savunuculuğu|||BEP Desteği|||Aile Destek Grubu',NULL),
('acev','AÇEV — Aile ve Çocuk Eğitimi Vakfı','İstanbul','ngo','Aile Eğitimi|||Erken Çocukluk|||Gelişim','Aile eğitimi ve erken çocukluk gelişimi alanında Türkiye''nin önde gelen sivil toplum kuruluşu. Anne-baba eğitim programları ve ev ziyareti hizmetleri sunar.','0212 281 11 54',NULL,'https://www.acev.org',NULL,NULL,'Levent, İstanbul',NULL,NULL,NULL,'Anne-Baba Okulu|||Ev Ziyareti Programları|||Erken Müdahale Eğitimi',NULL),
('otizm-vakfi','Türkiye Otizm Vakfı','İstanbul','ngo','Araştırma|||Farkındalık|||Aile Desteği','Otizm spektrum bozukluğu alanında araştırma, eğitim ve farkındalık projeleri yürüten vakıf. Aile destek programları ve bilgilendirme seminerleri düzenler.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Farkındalık Eğitimleri|||Araştırma Desteği|||Aile Seminerleri',NULL),
('engelsiz-yasam','Engelsiz Yaşam Derneği','Ankara','ngo','Bağımsız Yaşam|||İstihdam|||Haklar','Engelli bireylerin bağımsız yaşam becerilerini kazanmaları ve istihdam edilmeleri için çalışır. Hukuki danışmanlık ve toplumsal farkındalık faaliyetleri yürütür.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Bağımsız Yaşam Eğitimi|||İş Bulma Desteği|||Oryantasyon|||Hukuki Danışmanlık',NULL),
('ogbd','Otizm ve Gelişimsel Bozukluklar Derneği (OGBD)','İstanbul','ngo','Otizm|||Eğitim|||Aile Desteği','Otizm ve gelişimsel bozukluklar alanında aileleri bilgilendirmek, farkındalık oluşturmak ve destek grupları oluşturmak amacıyla kurulmuş dernek.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Aile Bilgilendirme|||Destek Grupları|||Seminerler',NULL),
('cocuk-gelisim-der','Türkiye Çocuk Gelişimi Derneği','Ankara','ngo','Çocuk Gelişimi|||Erken Müdahale|||Eğitim','Çocuk gelişimi uzmanlarını bir araya getiren mesleki dernek. Erken müdahale ve özel eğitim alanında rehberlik ve kaynak sağlar.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mesleki Rehberlik|||Kaynak Kütüphanesi|||Uzman Yönlendirme',NULL),
('ozak','Türkiye Özürlüler Araştırma Vakfı (ÖZAK)','Ankara','ngo','Araştırma|||Haklar|||Politika','Engelli bireylerin haklarına yönelik araştırma ve savunuculuk faaliyetleri yürüten vakıf. Politika önerileri ve raporlar hazırlar.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Araştırma|||Savunuculuk|||Politika Geliştirme',NULL),
('engelli-hak-fed','Türkiye Engelli Hakları Federasyonu','Ankara','ngo','Hak Savunuculuğu|||Politika|||Hukuki Destek','Engelli bireylerin haklarını savunan çatı federasyonu. Yasal düzenlemelerin takibi ve hak ihlali bildirimi konularında destek verir.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Hak Savunuculuğu|||Hukuki Danışmanlık|||İtiraz Desteği',NULL),
('erg','Eğitim Reformu Girişimi (ERG)','İstanbul','ngo','Eğitim Politikası|||Kaynaştırma|||Araştırma','Türkiye''de eğitim politikasını araştıran ve kapsayıcı eğitim için savunuculuk yapan sivil toplum kuruluşu. Kaynaştırma eğitimi alanında önemli raporlar yayımlar.',NULL,NULL,'https://www.egitimreformugirisimi.org',NULL,NULL,NULL,NULL,NULL,NULL,'Araştırma Raporları|||Politika Önerileri|||Kapsayıcı Eğitim Savunuculuğu',NULL),

-- Üniversite Hastaneleri — İstanbul
('cerrahpasa','İÜ-Cerrahpaşa — Çocuk Psikiyatri','İstanbul','university-hospital','Çocuk Psikiyatri|||OSB Tanı|||Nörogelişim','Türkiye''nin en köklü tıp fakültelerinden biri. OSB tanı süreci ve nörogelişimsel bozukluklar konusunda köklü deneyime sahip çocuk psikiyatri kliniği.','0212 414 30 00',NULL,NULL,NULL,NULL,'Cerrahpaşa, Fatih, İstanbul',true,NULL,'0–18 yaş','OSB Tanı|||İlaç Yönetimi|||Psikolojik Değerlendirme|||Nöropsikiyatri',NULL),
('marmara-u','Marmara Üniversitesi — Çocuk Psikiyatri','İstanbul','university-hospital','Çocuk Psikiyatri|||OSB|||DEHB|||Anksiyete','İstanbul''un önemli üniversite hastanelerinden biri. Çocuk ve ergen psikiyatrisi alanında güçlü akademik kadroya sahip; OSB tanı ve izleminde deneyimli.','0216 625 45 45',NULL,NULL,NULL,NULL,'Pendik, İstanbul',true,NULL,'0–18 yaş','OSB Tanı|||Psikiyatrik Değerlendirme|||Bilişsel Testler|||Terapi',NULL),
('sbu-haseki','Sağlık Bilimleri Üniversitesi Haseki EAH — Çocuk Psikiyatri','İstanbul','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','SBÜ bünyesindeki Haseki Eğitim ve Araştırma Hastanesi''nde aktif çocuk psikiyatri polikliniği. SGK anlaşmalı ve erişilebilir konumda.','0212 529 44 00',NULL,NULL,NULL,NULL,'Fatih, İstanbul',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||İlaç Yönetimi',NULL),
('sbu-bakirkoy','SBÜ Bakırköy Prof. Dr. Mazhar Osman Ruh Sağlığı EAH','İstanbul','university-hospital','Çocuk Psikiyatri|||Ergen Psikiyatri|||OSB','Türkiye''nin en büyük psikiyatri referans merkezlerinden biri. Çocuk ve ergen psikiyatri birimi ile gelişimsel bozukluklar alanında kapsamlı hizmet sunar.','0212 543 65 65',NULL,NULL,NULL,NULL,'Bakırköy, İstanbul',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Tanı|||Nöropsikiyatri|||Aile Danışmanlığı',NULL),
('koc-u','Koç Üniversitesi Hastanesi — Çocuk Nöroloji','İstanbul','private-hospital','Çocuk Nöroloji|||Epilepsi|||Nörogelişim','Modern altyapısı ve uzman kadrosuyla çocuk nöroloji ve nörogelişim alanında öne çıkan özel üniversite hastanesi.','0212 311 40 00',NULL,'https://www.kuh.ku.edu.tr','https://www.kuh.ku.edu.tr',NULL,'Davutpaşa, Zeytinburnu, İstanbul',false,NULL,'0–18 yaş','Çocuk Nöroloji|||EEG|||MRI|||Nöropsikiyatri',NULL),

-- Üniversite Hastaneleri — Ankara
('hacettepe','Hacettepe Üniversitesi — Çocuk Psikiyatri','Ankara','university-hospital','Çocuk Psikiyatri|||OSB|||ADOS Değerlendirme|||Nörogelişim','Çocuk psikiyatri alanında Türkiye''nin başlıca referans merkezi. ADOS-2 ve ADI-R ile kapsamlı standart OSB değerlendirmesi yapar; araştırma ve uygulama birlikte yürütülür.','0312 305 50 00',NULL,'https://hastane.hacettepe.edu.tr',NULL,NULL,'Sıhhiye, Çankaya, Ankara',true,NULL,'0–18 yaş','OSB Tanı|||ADOS-2|||ADI-R|||İlaç Tedavisi|||Aile Eğitimi',NULL),
('hacettepe-sbl','Hacettepe — Sağlık Bilimleri Fakültesi','Ankara','university-hospital','Ergoterapi|||Dil-Konuşma Terapisi|||Fizyoterapi','Türkiye''nin en güçlü ergoterapi, dil-konuşma terapisi ve fizyoterapi bölümlerine ev sahipliği yapar. OSB dahil nörogelişimsel bozuklukları olan çocuklara terapi verilir.','0312 305 15 59',NULL,NULL,NULL,NULL,'Hacettepe Kampüsü, Altındağ, Ankara',true,NULL,'0–18 yaş','Ergoterapi|||Dil-Konuşma Terapisi|||Duyu Bütünleme|||Fizyoterapi',NULL),
('ankara-u','Ankara Üniversitesi — Çocuk Psikiyatri','Ankara','university-hospital','Çocuk Psikiyatri|||OSB|||DEHB|||Öğrenme Güçlüğü','Köklü tıp fakültesinin çocuk psikiyatri kliniği; OSB, DEHB ve öğrenme güçlüğü alanında tanı ve tedavi hizmetleri sunar.','0312 508 20 00',NULL,NULL,NULL,NULL,'Cebeci, Mamak, Ankara',true,NULL,'0–18 yaş','Psikiyatrik Değerlendirme|||Bilişsel Test|||Terapi|||İlaç Yönetimi',NULL),
('gazi-u','Gazi Üniversitesi — Çocuk Nöroloji & Psikiyatri','Ankara','university-hospital','Çocuk Nöroloji|||Epilepsi|||OSB|||Nörogelişim','Nörogelişimsel bozuklukların tanı ve takibinde güçlü bir referans merkezi. Çocuk nöroloji ve psikiyatri birimleri birlikte çalışmaktadır.','0312 202 50 00',NULL,NULL,NULL,NULL,'Beşevler, Yenimahalle, Ankara',true,NULL,'0–18 yaş','EEG|||MRI|||Çocuk Nöroloji|||Çocuk Psikiyatri|||Nöropsikoloji',NULL),
('bayindir','Bayındır Hastanesi — Çocuk Nöroloji','Ankara','private-hospital','Çocuk Nöroloji|||Çocuk Psikiyatri|||OSB','Ankara''nın köklü özel hastanelerinden biri. Çocuk nöroloji ve psikiyatri alanında deneyimli uzman kadrosuyla hizmet verir.','0312 287 90 00',NULL,NULL,NULL,NULL,'Kavaklıdere, Çankaya, Ankara',false,NULL,'0–18 yaş','Çocuk Nöroloji|||Çocuk Psikiyatri|||EEG|||Nöropsikoloji',NULL),
('guven','Güven Hastanesi — Çocuk Sağlığı','Ankara','private-hospital','Çocuk Gelişimi|||Çocuk Nöroloji','Ankara''nın köklü özel hastanelerinden Güven Hastanesi''nde çocuk sağlığı ve nöroloji poliklinikleri faaliyet göstermektedir.','0312 457 27 27',NULL,NULL,NULL,NULL,'Kavaklidere, Çankaya, Ankara',false,NULL,'0–18 yaş','Çocuk Nöroloji|||Gelişimsel Değerlendirme',NULL),

-- Üniversite Hastaneleri — İzmir
('ege-u','Ege Üniversitesi — Çocuk Psikiyatri','İzmir','university-hospital','Çocuk Psikiyatri|||OSB Tanı|||DEHB','Ege Bölgesi''nin referans çocuk psikiyatri merkezi. OSB tanı ve izlemi konusunda uzmanlaşmış akademik kadrosuyla kapsamlı hizmet sunar.','0232 390 10 10',NULL,NULL,NULL,NULL,'Bornova, İzmir',true,NULL,'0–18 yaş','OSB Tanı|||ADOS-2|||Çocuk Psikiyatri|||Psikolojik Test',NULL),
('deu','Dokuz Eylül Üniversitesi — Çocuk Psikiyatri','İzmir','university-hospital','OSB Tanı|||Çocuk Psikiyatri|||Nörogelişim','OSB tanı ve izleminde standart ölçüm araçlarını kullanan, deneyimli akademik kadroya sahip çocuk psikiyatri kliniği.','0232 412 12 12',NULL,NULL,NULL,NULL,'İnciraltı, Balçova, İzmir',true,NULL,'0–18 yaş','OSB Değerlendirme|||ADOS-2|||ADI-R|||Aile Danışmanlığı',NULL),
('celal-bayar','Manisa Celal Bayar Üniversitesi — Çocuk Psikiyatri','Manisa','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','Ege bölgesinin iç kesimlerinde önemli bir referans merkezi. Çocuk psikiyatri kliniği OSB ve diğer nörogelişimsel bozuklukların tanı ve tedavisinde hizmet vermektedir.','0236 233 96 00',NULL,NULL,NULL,NULL,'Yunusemre, Manisa',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||Psikoloji',NULL),
('pamukkale-u','Pamukkale Üniversitesi — Çocuk Psikiyatri','Denizli','university-hospital','Çocuk Psikiyatri|||OSB|||DEHB','Denizli ve çevresi için önemli referans hastane. Çocuk ve ergen psikiyatrisi alanında tanı ve tedavi hizmetleri sunmaktadır.','0258 296 50 00',NULL,NULL,NULL,NULL,'Kınıklı, Pamukkale, Denizli',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Tanı|||Psikoloji',NULL),

-- Bursa & Marmara
('uludag','Uludağ Üniversitesi — Çocuk Psikiyatri','Bursa','university-hospital','Çocuk Psikiyatri|||OSB|||Öğrenme Güçlüğü','Bursa bölgesinin referans çocuk psikiyatri merkezi. OSB, DEHB ve öğrenme güçlüğü alanında kapsamlı tanı ve tedavi hizmetleri sunar.','0224 295 00 00',NULL,NULL,NULL,NULL,'Görükle, Nilüfer, Bursa',true,NULL,'0–18 yaş','OSB Değerlendirme|||Çocuk Psikiyatri|||Psikoloji|||Dil-Konuşma Terapisi',NULL),
('trakya-u','Trakya Üniversitesi — Çocuk Psikiyatri','Edirne','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','Trakya Bölgesi''nin tek üniversite hastanesi. Çocuk psikiyatri birimi OSB ve diğer gelişimsel bozukluklar için tanı ve izlem hizmeti vermektedir.','0284 235 76 41',NULL,NULL,NULL,NULL,'Merkez, Edirne',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Tanı|||Aile Danışmanlığı',NULL),
('balikesir-u','Balıkesir Üniversitesi — Çocuk Psikiyatri','Balıkesir','university-hospital','Çocuk Psikiyatri|||OSB','Balıkesir ve çevresi için çocuk psikiyatri hizmetleri sunan üniversite hastanesi.','0266 612 14 00',NULL,NULL,NULL,NULL,'Bigadiç Yolu, Balıkesir',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||Psikoloji',NULL),
('kocaeli-u','Kocaeli Üniversitesi — Çocuk Psikiyatri','Kocaeli','university-hospital','Çocuk Psikiyatri|||OSB|||DEHB','Kocaeli ve çevre illeri için referans çocuk psikiyatri merkezi. Nörogelişimsel bozukluklar alanında tanı ve tedavi hizmetleri sunar.','0262 303 70 70',NULL,NULL,NULL,NULL,'Umuttepe, İzmit, Kocaeli',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Tanı|||Nöropsikoloji',NULL),
('sakarya-u','Sakarya Üniversitesi — Çocuk Psikiyatri','Sakarya','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','Sakarya ve çevresi için önemli referans merkezi. Çocuk psikiyatri alanında tanı ve tedavi hizmetleri verilmektedir.','0264 295 40 00',NULL,NULL,NULL,NULL,'Erenler, Sakarya',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB|||Psikoloji',NULL),

-- Akdeniz
('akdeniz','Akdeniz Üniversitesi — Çocuk Psikiyatri','Antalya','university-hospital','Çocuk Psikiyatri|||OSB|||DEHB','Akdeniz Bölgesi''nin referans çocuk psikiyatri merkezi. OSB tanı ve izleminde deneyimli kadrosuyla kapsamlı hizmet sunar.','0242 249 60 00',NULL,NULL,NULL,NULL,'Konyaaltı, Antalya',true,NULL,'0–18 yaş','OSB Değerlendirme|||Çocuk Psikiyatri|||Psikoloji|||Aile Terapisi',NULL),
('cukurova','Çukurova Üniversitesi — Çocuk Psikiyatri','Adana','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','Güney Türkiye''nin en büyük üniversite hastanelerinden biri. Çocuk psikiyatri kliniği OSB ve diğer nörogelişimsel bozuklukların tanı ve tedavisinde etkin rol oynar.','0322 338 63 84',NULL,NULL,NULL,NULL,'Balcalı, Sarıçam, Adana',true,NULL,'0–18 yaş','OSB Tanı|||Psikiyatrik Değerlendirme|||İlaç Yönetimi',NULL),
('mersin-u','Mersin Üniversitesi — Çocuk Psikiyatri','Mersin','university-hospital','Çocuk Psikiyatri|||OSB|||DEHB','Mersin ve çevresi için referans çocuk psikiyatri merkezi. Nörogelişimsel bozukluklar alanında tanı ve tedavi hizmetleri verilmektedir.','0324 241 00 00',NULL,NULL,NULL,NULL,'Çiftlikköy, Yenişehir, Mersin',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||Psikoloji',NULL),
('hatay-mku','İskenderun Teknik Üniversitesi — Defne Devlet Hastanesi','Hatay','university-hospital','Çocuk Psikiyatri|||OSB','Hatay bölgesinde çocuk psikiyatri ve nörogelişimsel bozukluklar alanında hizmet veren hastane.','0326 227 10 00',NULL,NULL,NULL,NULL,'Antakya, Hatay',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Tanı|||Psikoloji',NULL),
('sdu','Süleyman Demirel Üniversitesi — Çocuk Psikiyatri','Isparta','university-hospital','Çocuk Psikiyatri|||OSB|||DEHB','Isparta ve Göller Bölgesi için referans çocuk psikiyatri merkezi. Nörogelişimsel bozuklukların tanı ve takibinde hizmet vermektedir.','0246 232 95 00',NULL,NULL,NULL,NULL,'Merkez, Isparta',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||Nöropsikoloji',NULL),

-- İç Anadolu
('selcuk','Selçuk Üniversitesi — Çocuk Nöroloji & Psikiyatri','Konya','university-hospital','Çocuk Nöroloji|||Çocuk Psikiyatri|||OSB','İç Anadolu bölgesinin önemli üniversite hastanelerinden biri. Çocuk nöroloji ve psikiyatri birimleri koordineli şekilde hizmet vermektedir.','0332 224 40 00',NULL,NULL,NULL,NULL,'Selçuklu, Konya',true,NULL,'0–18 yaş','EEG|||Çocuk Nöroloji|||Çocuk Psikiyatri|||OSB Değerlendirme',NULL),
('erciyes','Erciyes Üniversitesi — Çocuk Psikiyatri','Kayseri','university-hospital','Çocuk Psikiyatri|||OSB|||DEHB','Orta Anadolu''nun referans çocuk psikiyatri merkezi. OSB ve DEHB tanı ile tedavisinde deneyimli akademik kadroya sahiptir.','0352 207 66 66',NULL,NULL,NULL,NULL,'Melikgazi, Kayseri',true,NULL,'0–18 yaş','OSB Tanı|||Çocuk Psikiyatri|||Psikoloji|||Aile Danışmanlığı',NULL),
('ogu','Eskişehir Osmangazi Üniversitesi — Çocuk Psikiyatri','Eskişehir','university-hospital','Çocuk Psikiyatri|||OSB|||DEHB','Eskişehir ve çevresi için referans merkezi. Çocuk psikiyatri kliniği nörogelişimsel bozukluklar alanında aktif hizmet vermektedir.','0222 239 29 79',NULL,NULL,NULL,NULL,'Odunpazarı, Eskişehir',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB|||Aile Danışmanlığı',NULL),
('cumhuriyet-u','Sivas Cumhuriyet Üniversitesi — Çocuk Psikiyatri','Sivas','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','Sivas ve çevresi için referans çocuk psikiyatri merkezi. Nörogelişimsel bozukluklar alanında tanı ve tedavi hizmetleri sunmaktadır.','0346 258 00 00',NULL,NULL,NULL,NULL,'Merkez, Sivas',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||Psikoloji',NULL),

-- Karadeniz
('ktu','Karadeniz Teknik Üniversitesi — Çocuk Psikiyatri','Trabzon','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','Doğu Karadeniz''in referans çocuk psikiyatri merkezi. OSB ve nörogelişimsel bozukluklar alanında tanı ve izlem hizmetleri verir.','0462 377 50 00',NULL,NULL,NULL,NULL,'Ortahisar, Trabzon',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||Psikoloji',NULL),
('omu','Ondokuz Mayıs Üniversitesi — Çocuk Psikiyatri','Samsun','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','Orta Karadeniz''in referans hastanesi. Çocuk ve ergen psikiyatri kliniği OSB başta olmak üzere nörogelişimsel bozukluklar için hizmet vermektedir.','0362 312 19 19',NULL,NULL,NULL,NULL,'Atakum, Samsun',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||Aile Danışmanlığı',NULL),
('rize-u','Recep Tayyip Erdoğan Üniversitesi — Çocuk Psikiyatri','Rize','university-hospital','Çocuk Psikiyatri|||OSB','Doğu Karadeniz kıyı şeridinde çocuk psikiyatri ve nörogelişimsel bozukluklar alanında hizmet veren üniversite hastanesi.','0464 213 04 97',NULL,NULL,NULL,NULL,'Merkez, Rize',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Tanı|||Psikoloji',NULL),
('beu','Bülent Ecevit Üniversitesi — Çocuk Psikiyatri','Zonguldak','university-hospital','Çocuk Psikiyatri|||OSB|||DEHB','Batı Karadeniz bölgesi için önemli referans hastane. Çocuk psikiyatri kliniği OSB ve diğer nörogelişimsel bozuklukları için hizmet vermektedir.','0372 261 21 00',NULL,NULL,NULL,NULL,'Kozlu, Zonguldak',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||Psikoloji',NULL),
('aibu','Abant İzzet Baysal Üniversitesi — Çocuk Psikiyatri','Bolu','university-hospital','Çocuk Psikiyatri|||OSB','Bolu ve çevresi için çocuk psikiyatri hizmetleri sunan üniversite hastanesi.','0374 253 46 56',NULL,NULL,NULL,NULL,'Merkez, Bolu',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Tanı|||Aile Danışmanlığı',NULL),

-- Doğu & Güneydoğu
('gaziantep-u','Gaziantep Üniversitesi — Çocuk Psikiyatri','Gaziantep','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','Güneydoğu Anadolu bölgesinin referans çocuk psikiyatri merkezi. OSB ve nörogelişimsel bozukluklar alanında kapsamlı değerlendirme yapılmaktadır.','0342 360 60 60',NULL,NULL,NULL,NULL,'Şehitkamil, Gaziantep',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||İlaç Yönetimi',NULL),
('harran-u','Harran Üniversitesi — Çocuk Psikiyatri','Şanlıurfa','university-hospital','Çocuk Psikiyatri|||OSB','Güneydoğu Anadolu''da çocuk psikiyatri hizmetleri veren üniversite hastanesi.','0414 318 30 00',NULL,NULL,NULL,NULL,'Osmanbey, Haliliye, Şanlıurfa',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Tanı|||Psikoloji',NULL),
('dicle','Dicle Üniversitesi — Çocuk Psikiyatri','Diyarbakır','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','Güneydoğu Türkiye''nin önemli referans üniversite hastanelerinden biri. Çocuk ve ergen psikiyatri kliniği nörogelişimsel bozukluklar alanında aktif hizmet vermektedir.','0412 248 80 01',NULL,NULL,NULL,NULL,'Sur, Diyarbakır',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Tanı|||Psikolojik Test',NULL),
('firat-u','Fırat Üniversitesi — Çocuk Psikiyatri','Elazığ','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','Doğu Anadolu''nun önemli referans merkezlerinden biri. Çocuk psikiyatri kliniği OSB dahil nörogelişimsel bozuklukların tanı ve tedavisinde hizmet vermektedir.','0424 233 35 55',NULL,NULL,NULL,NULL,'Merkez, Elazığ',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||Psikoloji',NULL),
('atauni','Atatürk Üniversitesi — Çocuk Psikiyatri','Erzurum','university-hospital','Çocuk Psikiyatri|||Nörogelişim|||OSB','Doğu Anadolu''nun en büyük üniversite hastanesi ve bölgenin başlıca çocuk psikiyatri referans merkezi.','0442 344 68 00',NULL,NULL,NULL,NULL,'Yakutiye, Erzurum',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB|||Nöroloji|||Psikolojik Test',NULL),
('inonu','İnönü Üniversitesi — Çocuk Psikiyatri','Malatya','university-hospital','Çocuk Psikiyatri|||OSB|||Nörogelişim','Doğu Anadolu için önemli referans merkezi. Çocuk psikiyatri birimi OSB başta olmak üzere nörogelişimsel bozuklukların tanı ve takibini yapar.','0422 341 06 60',NULL,NULL,NULL,NULL,'Battalgazi, Malatya',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Değerlendirme|||Psikoloji',NULL),
('van-yyu','Van Yüzüncü Yıl Üniversitesi — Çocuk Psikiyatri','Van','university-hospital','Çocuk Psikiyatri|||OSB','Van ve Doğu Anadolu''nun uzak kesimlerinde yaşayan aileler için ulaşılabilir referans çocuk psikiyatri merkezi.','0432 215 07 35',NULL,NULL,NULL,NULL,'Tuşba, Van',true,NULL,'0–18 yaş','Çocuk Psikiyatri|||OSB Tanı|||Psikoloji',NULL),

-- Özel Hastaneler
('acibadem','Acıbadem Hastaneleri — Çocuk Gelişim','İstanbul','private-hospital','Çocuk Gelişimi|||Erken Müdahale|||Nörogelişim','Birden fazla şubesiyle İstanbul''da çok disiplinli erken müdahale ve çocuk gelişim programları sunan özel hastane zinciri.','0216 500 43 00',NULL,'https://www.acibadem.com.tr',NULL,NULL,NULL,false,NULL,'0–12 yaş','Erken Müdahale|||Dil-Konuşma Terapisi|||Ergoterapi|||Psikoloji',NULL),
('anadolu','Anadolu Sağlık Merkezi — Çocuk Nöroloji','Kocaeli','private-hospital','Çocuk Nöroloji|||Çocuk Psikiyatri|||Nörogelişim','Johns Hopkins Medicine iş birliğiyle çalışan, uluslararası standartlarda hizmet veren özel hastane.','0262 678 55 55',NULL,'https://www.anadolusaglik.org',NULL,NULL,'Gebze, Kocaeli',false,NULL,'0–18 yaş','Çocuk Nöroloji|||MRI|||EEG|||Nöropsikiyatri',NULL),
('medicana','Medicana Hastaneleri — Çocuk Sağlığı','İstanbul','private-hospital','Çocuk Nöroloji|||Çocuk Gelişimi','İstanbul''da birden fazla şubesi bulunan özel hastane zincirinin çocuk sağlığı ve nöroloji birimleri.','0212 444 44 84',NULL,'https://www.medicana.com.tr',NULL,NULL,NULL,false,NULL,'0–18 yaş','Çocuk Nöroloji|||Gelişimsel Değerlendirme|||EEG',NULL),
('medical-park','Medical Park Hastaneleri — Çocuk Nöroloji','İstanbul','private-hospital','Çocuk Nöroloji|||Çocuk Psikiyatri','Türkiye genelinde yaygın şube ağına sahip özel hastane zinciri.','0850 200 10 00',NULL,'https://www.medicalpark.com.tr',NULL,NULL,NULL,false,NULL,'0–18 yaş','Çocuk Nöroloji|||Çocuk Psikiyatri|||EEG|||MRI',NULL),
('florence','Florence Nightingale Hastanesi — Çocuk Nöroloji','İstanbul','private-hospital','Çocuk Nöroloji|||Epilepsi|||Nörogelişim','İstanbul''un köklü özel hastanelerinden biri. Çocuk nöroloji birimi epilepsi ve nörogelişimsel bozukluklar alanında uzmanlaşmıştır.','0212 224 49 50',NULL,'https://www.fnhastanesi.com.tr',NULL,NULL,'Şişli, İstanbul',false,NULL,'0–18 yaş','Çocuk Nöroloji|||EEG|||MRI|||Nöropsikiyatri',NULL),
('american-hospital','American Hospital — Çocuk Sağlığı','İstanbul','private-hospital','Çocuk Nöroloji|||Çocuk Gelişimi','Uluslararası standartlarda hizmet veren, JCI akreditasyonlu özel hastane.','0212 444 37 77',NULL,NULL,NULL,NULL,'Nişantaşı, Şişli, İstanbul',false,NULL,'0–18 yaş','Çocuk Nöroloji|||Gelişimsel Değerlendirme|||Nöropsikiyatri',NULL),

-- Özel Rehabilitasyon Merkezleri
('tohum-egitim','Tohum Otizm Eğitim Merkezi','İstanbul','private-rehab','ABA Terapisi|||Özel Eğitim|||Dil-Konuşma Terapisi','Tohum Otizm Vakfı bünyesinde faaliyet gösteren özel eğitim ve terapi merkezi. ABA temelli bireysel ve grup programları sunulmaktadır.','0212 257 75 00',NULL,'https://www.tohumotizm.org.tr',NULL,NULL,'Etiler, Beşiktaş, İstanbul',false,NULL,'2–12 yaş','ABA Terapisi|||Dil-Konuşma Terapisi|||Özel Eğitim|||Oyun Terapisi|||Aile Eğitimi',NULL),
('meb-rehab','MEB Onaylı Özel Eğitim & Rehabilitasyon Merkezleri','Tüm İller','private-rehab','Özel Eğitim|||ABA Terapisi|||Dil-Konuşma Terapisi|||Ergoterapi','MEB lisanslı özel eğitim ve rehabilitasyon merkezleri, RAM yönlendirmesi ve SGK onayıyla terapi ücretlerini kısmen devletten karşılayabilir.',NULL,NULL,'https://orgm.meb.gov.tr','https://orgm.meb.gov.tr','MEB Özel Eğitim',NULL,true,NULL,NULL,'Özel Eğitim|||ABA Terapisi|||Dil-Konuşma Terapisi|||Ergoterapi|||BEP Hazırlama','Önce RAM''a başvurun; RAM onayı ve SGK ilişkilendirmesi tamamlandıktan sonra merkez seçimi yapılır.'),
('ozel-egitim-ankara','Ankara Özel Eğitim Merkezleri','Ankara','private-rehab','ABA|||Dil-Konuşma|||Ergoterapi|||Özel Eğitim','Ankara''da MEB onaylı çok sayıda özel eğitim ve rehabilitasyon merkezi bulunmaktadır.',NULL,NULL,NULL,NULL,NULL,NULL,true,NULL,NULL,'ABA Terapisi|||Dil-Konuşma Terapisi|||Ergoterapi|||Sosyal Beceri Grubu|||Aile Eğitimi','Ankara İl MEB veya RAM üzerinden ilçenizdeki lisanslı merkezlere ulaşabilirsiniz.'),
('ozel-egitim-izmir','İzmir Özel Eğitim Merkezleri','İzmir','private-rehab','ABA|||Dil-Konuşma|||Ergoterapi|||Özel Eğitim','İzmir''de MEB onaylı özel eğitim ve rehabilitasyon merkezleri kapsamlı terapi hizmetleri sunmaktadır.',NULL,NULL,NULL,NULL,NULL,NULL,true,NULL,NULL,'ABA Terapisi|||Dil-Konuşma Terapisi|||Ergoterapi|||BEP Hazırlama','İzmir RAM''ına başvurarak ilçenizdeki lisanslı merkezlere yönlendirilmeyi talep edebilirsiniz.'),
('ozel-egitim-bursa','Bursa Özel Eğitim Merkezleri','Bursa','private-rehab','Özel Eğitim|||Dil-Konuşma|||ABA','Bursa''da MEB onaylı özel eğitim ve rehabilitasyon merkezleri bulunmaktadır.',NULL,NULL,NULL,NULL,NULL,NULL,true,NULL,NULL,'Özel Eğitim|||Dil-Konuşma Terapisi|||ABA|||Ergoterapi',NULL),
('ozel-egitim-antalya','Antalya Özel Eğitim Merkezleri','Antalya','private-rehab','Özel Eğitim|||Dil-Konuşma|||ABA','Antalya''da MEB onaylı özel eğitim ve rehabilitasyon merkezleri bulunmaktadır.',NULL,NULL,NULL,NULL,NULL,NULL,true,NULL,NULL,'Özel Eğitim|||Dil-Konuşma Terapisi|||ABA|||Sosyal Beceri Eğitimi',NULL),

-- Devlet Kurumları
('ram','RAM — Rehberlik ve Araştırma Merkezleri','Tüm İller','state','Eğitsel Değerlendirme|||BEP|||Kaynaştırma|||Özel Eğitim Yönlendirme','Tüm illerde MEB bünyesinde faaliyet gösterir. OSB tanısı alan çocuklar için eğitsel değerlendirme, uygun okul/program yönlendirmesi ve BEP koordinasyonu yapan ilk başvuru noktasıdır.',NULL,NULL,'https://orgm.meb.gov.tr','https://orgm.meb.gov.tr','MEB Özel Eğitim',NULL,NULL,true,NULL,'Eğitsel Değerlendirme|||BEP Koordinasyonu|||Kaynaştırma Yönlendirme|||Özel Eğitim Merkezi Yönlendirme|||Aile Danışmanlığı|||Psikolojik Destek','Tanı sonrası ilk adım RAM''dır. İlçenizdeki RAM''a tanı belgenizle başvurun.'),
('cozummer','ÇÖZÜM-MER — Engelli Aile Destek Merkezi','Tüm İller','state','Aile Desteği|||Sosyal Hizmet|||Hak Danışmanlığı|||Yönlendirme','Aile ve Sosyal Hizmetler Bakanlığı''na bağlı merkezler. Engelli bireylere ve ailelerine ücretsiz sosyal hizmet ve yönlendirme yapar.','183',NULL,'https://www.aile.gov.tr','https://www.aile.gov.tr','Aile Bakanlığı',NULL,NULL,true,NULL,'Ücretsiz Danışmanlık|||Sosyal Yardım Yönlendirme|||Hak Bilgilendirme|||Bakım Ücreti Başvurusu','ALO 183''ü arayarak sosyal destek ve yönlendirme alabilirsiniz. Ücretsizdir.'),
('sgk','SGK — Sosyal Güvenlik Kurumu','Tüm İller','state','Sağlık Hakları|||Rehabilitasyon Desteği|||İlaç Ödemesi','OSB tanılı çocukların özel eğitim ve rehabilitasyon merkezi giderlerini RAM yönlendirmesi sonrası karşılar.','170',NULL,'https://www.sgk.gov.tr',NULL,NULL,NULL,NULL,true,NULL,'Rehabilitasyon Gideri Karşılama|||İlaç Ödemesi|||Sağlık Kurulu Raporu Takibi','Önce RAM yönlendirmesi, ardından SGK anlaşmalı bir merkez seçimi gereklidir.'),
('aile-bakanlik','Aile ve Sosyal Hizmetler Bakanlığı','Tüm İller','state','Bakım Ücreti|||Sosyal Yardım|||Aile Desteği','Ağır engellilik raporuna sahip bireylere evde bakım ücreti öder.','183',NULL,'https://www.aile.gov.tr','https://www.aile.gov.tr','Aile Bakanlığı',NULL,NULL,true,NULL,'Evde Bakım Ücreti|||Sosyal Yardım|||Aile Danışmanlığı|||Engelli Kimlik Kartı Başvurusu',NULL),
('meb-ozel-egitim','MEB Özel Eğitim ve Rehberlik Hizmetleri GM','Tüm İller','state','Özel Eğitim Politikası|||BEP|||Kaynaştırma Standardı','Özel eğitim hizmetlerini düzenleyen MEB biriminin web sitesinde güncel mevzuat ve rehber belgeler yer almaktadır.',NULL,NULL,'https://orgm.meb.gov.tr',NULL,NULL,NULL,NULL,true,NULL,'Mevzuat Bilgisi|||BEP Rehberleri|||Kaynaştırma Standartları|||Öğretmen Eğitim Materyalleri',NULL),
('iskur','İŞKUR','Tüm İller','state','Engelli İstihdamı|||Mesleki Eğitim|||Kariyer Danışmanlığı','Engelli bireylerin istihdamını destekleyen devlet kurumu.','170',NULL,'https://www.iskur.gov.tr',NULL,NULL,NULL,NULL,true,NULL,'İş ve Meslek Danışmanlığı|||Mesleki Eğitim Kursları|||İşe Yerleştirme|||Korumalı İşyeri Desteği',NULL),
('cimer','CİMER — Cumhurbaşkanlığı İletişim Merkezi','Tüm İller','state','Şikayet|||Başvuru|||Hak Arama','Devlet kurumlarına yönelik şikayet ve başvuruların iletildiği merkezi platform.','150',NULL,'https://www.cimer.gov.tr','https://www.cimer.gov.tr','CİMER',NULL,NULL,true,NULL,'Şikayet Bildirimi|||Başvuru Takibi|||Kamu Kurumu Şikayeti',NULL),
('ombudsman','Kamu Denetçiliği Kurumu (Ombudsman)','Ankara','state','Hak Arama|||İdari Şikayet|||Hukuki Yol','İdari işlemler hakkındaki şikayetleri inceleyen bağımsız devlet kurumu. RAM veya MEB kararlarına itiraz, BEP ihlali gibi durumlarda başvurulabilir.','0312 465 22 00',NULL,'https://www.ombudsman.gov.tr',NULL,NULL,NULL,NULL,true,NULL,'İdari Şikayet İnceleme|||Bağımsız Denetim|||Tavsiye Kararı',NULL)
ON CONFLICT (id) DO NOTHING;
