ALTER TABLE users ADD COLUMN IF NOT EXISTS consent_ai_analysis BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS consent_ai_analysis_date TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS consent_emergency_card BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS consent_emergency_card_date TIMESTAMP;
